services:
    # postgres:
    #     image: postgres
    #     environment:
    #         POSTGRES_DB: ${POSTGRES_DB}
    #         POSTGRES_USER: ${POSTGRES_USER}
    #         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #     restart: unless-stopped
    #     volumes:
    #         - postgres-data:/var/lib/postgresql/data
    #     ports:
    #         - 5432:5432
    #     healthcheck:
    #         test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #     networks:
    #         - app_network

    backend:
        build: 
            context: ./backend/
            dockerfile: ./Dockerfile
        image: backend-api:latest
        environment:
            API_KEY_NAME: ${API_KEY_NAME}
            MOCK_API_KEY: ${API_MOCK_KEY}
        restart: unless-stopped
        ports:
            - 8090:8090
        networks:
            - app-network


volumes:
    postgres-data:
networks:
    app-network: