# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  backend-lint-and-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name: Format
        run: ruff format
        
      - name: Check fix
        run: ruff check --fix

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./backend/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.14"

      - name: Install the project and local dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest

  frontend-lint-and-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run Biome lint
        run: bun run lint
      
      - name: Run tests
        run: bun run test:ci
    